# GitHub Action for SSG - Static Site Generator
# Usage in workflow:
#   - uses: spagu/ssg@v1
#     with:
#       source: 'my-content-folder'
#       template: 'krowy'
#       domain: 'example.com'

name: "SSG - Static Site Generator"
description: "Generate static sites from Markdown content with YAML frontmatter"
author: "spagu"

branding:
  icon: "file-text"
  color: "green"

inputs:
  source:
    description: "Content source folder name (inside content/ directory)"
    required: true
  template:
    description: "Template name to use (inside templates/ directory)"
    required: true
    default: "simple"
  domain:
    description: "Target domain for the generated site"
    required: true
  version:
    description: "SSG version to use (default: latest)"
    required: false
    default: "latest"
  content-dir:
    description: "Path to content directory (default: content)"
    required: false
    default: "content"
  templates-dir:
    description: "Path to templates directory (default: templates)"
    required: false
    default: "templates"
  output-dir:
    description: "Path to output directory (default: output)"
    required: false
    default: "output"
  webp:
    description: "Convert images to WebP format (true/false)"
    required: false
    default: "false"
  webp-quality:
    description: "WebP compression quality 1-100 (default: 60)"
    required: false
    default: "60"
  zip:
    description: "Create ZIP file for Cloudflare Pages deployment (true/false)"
    required: false
    default: "false"
  minify:
    description: "Minify HTML, CSS, and JS output (true/false)"
    required: false
    default: "false"
  clean:
    description: "Clean output directory before build (true/false)"
    required: false
    default: "false"

outputs:
  output-path:
    description: "Path to the generated site output directory"
    value: ${{ steps.generate.outputs.output-path }}
  zip-file:
    description: "Path to the generated ZIP file (if --zip was used)"
    value: ${{ steps.generate.outputs.zip-file }}
  zip-size:
    description: "Size of the generated ZIP file in bytes"
    value: ${{ steps.generate.outputs.zip-size }}

runs:
  using: "composite"
  steps:
    - name: Download SSG binary
      id: download
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"

        # Determine OS and architecture
        case "$RUNNER_OS" in
          Linux)  OS="linux" ;;
          macOS)  OS="darwin" ;;
          Windows) OS="windows" ;;
          *) echo "::error::Unsupported OS: $RUNNER_OS"; exit 1 ;;
        esac

        case "$RUNNER_ARCH" in
          X64)   ARCH="amd64" ;;
          ARM64) ARCH="arm64" ;;
          *) echo "::error::Unsupported architecture: $RUNNER_ARCH"; exit 1 ;;
        esac

        # Get latest version if not specified
        if [[ "$VERSION" == "latest" ]]; then
          VERSION=$(curl -sL https://api.github.com/repos/spagu/ssg/releases/latest | grep '"tag_name"' | cut -d'"' -f4)
          if [[ -z "$VERSION" ]]; then
            echo "::error::Failed to get latest version"
            exit 1
          fi
        fi

        echo "ðŸ“¦ Downloading SSG $VERSION for $OS/$ARCH..."

        # Build download URL
        if [[ "$OS" == "windows" ]]; then
          ARCHIVE="ssg-${OS}-${ARCH}.zip"
        else
          ARCHIVE="ssg-${OS}-${ARCH}.tar.gz"
        fi

        URL="https://github.com/spagu/ssg/releases/download/${VERSION}/${ARCHIVE}"

        # Download and extract
        echo "ðŸ”— URL: $URL"
        curl -sL "$URL" -o "/tmp/$ARCHIVE"

        if [[ "$OS" == "windows" ]]; then
          unzip -q "/tmp/$ARCHIVE" -d /tmp/ssg-bin
        else
          mkdir -p /tmp/ssg-bin
          tar -xzf "/tmp/$ARCHIVE" -C /tmp/ssg-bin
        fi

        # Make executable and add to PATH
        chmod +x /tmp/ssg-bin/ssg*
        echo "/tmp/ssg-bin" >> $GITHUB_PATH

        echo "âœ… SSG $VERSION installed successfully"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Install cwebp (for WebP conversion)
      if: ${{ inputs.webp == 'true' }}
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update && sudo apt-get install -y webp
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install webp
        else
          echo "::warning::WebP tools not available on Windows, skipping WebP conversion"
        fi

    - name: Generate site
      id: generate
      shell: bash
      run: |
        # Build flags
        FLAGS=""
        if [[ "${{ inputs.webp }}" == "true" ]]; then
          FLAGS="$FLAGS --webp --webp-quality=${{ inputs.webp-quality }}"
        fi
        if [[ "${{ inputs.zip }}" == "true" ]]; then
          FLAGS="$FLAGS --zip"
        fi
        if [[ "${{ inputs.minify }}" == "true" ]]; then
          FLAGS="$FLAGS --minify-all"
        fi
        if [[ "${{ inputs.clean }}" == "true" ]]; then
          FLAGS="$FLAGS --clean"
        fi

        # Check if content directory exists
        if [[ ! -d "${{ inputs.content-dir }}/${{ inputs.source }}" ]]; then
          echo "::error::Content source directory not found: ${{ inputs.content-dir }}/${{ inputs.source }}"
          exit 1
        fi

        # Check if templates exist, copy from action repo if not
        if [[ ! -d "${{ inputs.templates-dir }}/${{ inputs.template }}" ]]; then
          if [[ -d "${{ github.action_path }}/templates/${{ inputs.template }}" ]]; then
            echo "ðŸ“ Copying template '${{ inputs.template }}' from action..."
            mkdir -p "${{ inputs.templates-dir }}"
            cp -r "${{ github.action_path }}/templates/${{ inputs.template }}" "${{ inputs.templates-dir }}/"
          else
            echo "::error::Template directory not found: ${{ inputs.templates-dir }}/${{ inputs.template }}"
            exit 1
          fi
        fi

        # Run generator
        echo "::group::Running SSG"
        ssg "${{ inputs.source }}" "${{ inputs.template }}" "${{ inputs.domain }}" \
          --content-dir="${{ inputs.content-dir }}" \
          --templates-dir="${{ inputs.templates-dir }}" \
          --output-dir="${{ inputs.output-dir }}" \
          $FLAGS
        echo "::endgroup::"

        # Set outputs
        echo "output-path=${{ inputs.output-dir }}" >> $GITHUB_OUTPUT

        # Handle ZIP output
        if [[ "${{ inputs.zip }}" == "true" ]]; then
          ZIP_FILE="${{ inputs.domain }}.zip"
          if [[ -f "$ZIP_FILE" ]]; then
            ZIP_SIZE=$(stat -f%z "$ZIP_FILE" 2>/dev/null || stat --format=%s "$ZIP_FILE")
            echo "zip-file=$ZIP_FILE" >> $GITHUB_OUTPUT
            echo "zip-size=$ZIP_SIZE" >> $GITHUB_OUTPUT
            echo "ðŸ“¦ ZIP created: $ZIP_FILE ($((ZIP_SIZE / 1024 / 1024)) MB)"
          fi
        fi
