// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MDDBClient is the client API for MDDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MDDBClient interface {
	// Add or update a document
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Document, error)
	// Add or update multiple documents in a single transaction (batch)
	AddBatch(ctx context.Context, in *AddBatchRequest, opts ...grpc.CallOption) (*AddBatchResponse, error)
	// Delete multiple documents in a single transaction (batch)
	DeleteBatch(ctx context.Context, in *DeleteBatchRequest, opts ...grpc.CallOption) (*DeleteBatchResponse, error)
	// Update multiple documents in a single transaction (batch)
	UpdateBatch(ctx context.Context, in *UpdateBatchRequest, opts ...grpc.CallOption) (*UpdateBatchResponse, error)
	// Get a document by key and language
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Document, error)
	// Search documents with filters
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Export documents (streaming)
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (MDDB_ExportClient, error)
	// Create database backup
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	// Restore database from backup
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	// Truncate revision history
	Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*TruncateResponse, error)
	// Get server statistics
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Vector/semantic search using embeddings
	VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error)
	// Reindex embeddings for a collection
	VectorReindex(ctx context.Context, in *VectorReindexRequest, opts ...grpc.CallOption) (*VectorReindexResponse, error)
	// Get vector/embedding statistics
	VectorStats(ctx context.Context, in *VectorStatsRequest, opts ...grpc.CallOption) (*VectorStatsResponse, error)
	// Import document from URL
	ImportURL(ctx context.Context, in *ImportURLRequest, opts ...grpc.CallOption) (*Document, error)
	// Set TTL on a document
	SetTTL(ctx context.Context, in *SetTTLRequest, opts ...grpc.CallOption) (*Document, error)
	// Full-text search
	FTS(ctx context.Context, in *FTSRequest, opts ...grpc.CallOption) (*FTSResponse, error)
	// Hybrid search (combines FTS + vector search)
	HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error)
	// Register a webhook
	RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*WebhookProto, error)
	// List webhooks
	ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error)
	// Delete a webhook
	DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*DeleteWebhookResponse, error)
	// Set JSON Schema for a collection's metadata validation
	SetSchema(ctx context.Context, in *SetSchemaRequest, opts ...grpc.CallOption) (*SetSchemaResponse, error)
	// Get JSON Schema for a collection
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	// Delete JSON Schema for a collection (disables validation)
	DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error)
	// List all collection schemas
	ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error)
	// Validate document metadata against collection schema
	ValidateDocument(ctx context.Context, in *ValidateDocumentRequest, opts ...grpc.CallOption) (*ValidateDocumentResponse, error)
	// Partial document update (meta and/or content independently)
	UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// Get document metadata only (without content)
	GetDocumentMeta(ctx context.Context, in *GetDocumentMetaRequest, opts ...grpc.CallOption) (*GetDocumentMetaResponse, error)
	// Zero-shot document classification using embedding similarity
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
}

type mDDBClient struct {
	cc grpc.ClientConnInterface
}

func NewMDDBClient(cc grpc.ClientConnInterface) MDDBClient {
	return &mDDBClient{cc}
}

func (c *mDDBClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) AddBatch(ctx context.Context, in *AddBatchRequest, opts ...grpc.CallOption) (*AddBatchResponse, error) {
	out := new(AddBatchResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/AddBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) DeleteBatch(ctx context.Context, in *DeleteBatchRequest, opts ...grpc.CallOption) (*DeleteBatchResponse, error) {
	out := new(DeleteBatchResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/DeleteBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) UpdateBatch(ctx context.Context, in *UpdateBatchRequest, opts ...grpc.CallOption) (*UpdateBatchResponse, error) {
	out := new(UpdateBatchResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/UpdateBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (MDDB_ExportClient, error) {
	stream, err := c.cc.NewStream(ctx, &MDDB_ServiceDesc.Streams[0], "/mddb.MDDB/Export", opts...)
	if err != nil {
		return nil, err
	}
	x := &mDDBExportClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MDDB_ExportClient interface {
	Recv() (*ExportChunk, error)
	grpc.ClientStream
}

type mDDBExportClient struct {
	grpc.ClientStream
}

func (x *mDDBExportClient) Recv() (*ExportChunk, error) {
	m := new(ExportChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mDDBClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/Backup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*TruncateResponse, error) {
	out := new(TruncateResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/Truncate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error) {
	out := new(VectorSearchResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/VectorSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) VectorReindex(ctx context.Context, in *VectorReindexRequest, opts ...grpc.CallOption) (*VectorReindexResponse, error) {
	out := new(VectorReindexResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/VectorReindex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) VectorStats(ctx context.Context, in *VectorStatsRequest, opts ...grpc.CallOption) (*VectorStatsResponse, error) {
	out := new(VectorStatsResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/VectorStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) ImportURL(ctx context.Context, in *ImportURLRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/ImportURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) SetTTL(ctx context.Context, in *SetTTLRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/SetTTL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) FTS(ctx context.Context, in *FTSRequest, opts ...grpc.CallOption) (*FTSResponse, error) {
	out := new(FTSResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/FTS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error) {
	out := new(HybridSearchResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/HybridSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*WebhookProto, error) {
	out := new(WebhookProto)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/RegisterWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error) {
	out := new(ListWebhooksResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/ListWebhooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*DeleteWebhookResponse, error) {
	out := new(DeleteWebhookResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/DeleteWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) SetSchema(ctx context.Context, in *SetSchemaRequest, opts ...grpc.CallOption) (*SetSchemaResponse, error) {
	out := new(SetSchemaResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/SetSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/GetSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error) {
	out := new(DeleteSchemaResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/DeleteSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error) {
	out := new(ListSchemasResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/ListSchemas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) ValidateDocument(ctx context.Context, in *ValidateDocumentRequest, opts ...grpc.CallOption) (*ValidateDocumentResponse, error) {
	out := new(ValidateDocumentResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/ValidateDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/UpdateDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) GetDocumentMeta(ctx context.Context, in *GetDocumentMetaRequest, opts ...grpc.CallOption) (*GetDocumentMetaResponse, error) {
	out := new(GetDocumentMetaResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/GetDocumentMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDB/Classify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MDDBServer is the server API for MDDB service.
// All implementations must embed UnimplementedMDDBServer
// for forward compatibility
type MDDBServer interface {
	// Add or update a document
	Add(context.Context, *AddRequest) (*Document, error)
	// Add or update multiple documents in a single transaction (batch)
	AddBatch(context.Context, *AddBatchRequest) (*AddBatchResponse, error)
	// Delete multiple documents in a single transaction (batch)
	DeleteBatch(context.Context, *DeleteBatchRequest) (*DeleteBatchResponse, error)
	// Update multiple documents in a single transaction (batch)
	UpdateBatch(context.Context, *UpdateBatchRequest) (*UpdateBatchResponse, error)
	// Get a document by key and language
	Get(context.Context, *GetRequest) (*Document, error)
	// Search documents with filters
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Export documents (streaming)
	Export(*ExportRequest, MDDB_ExportServer) error
	// Create database backup
	Backup(context.Context, *BackupRequest) (*BackupResponse, error)
	// Restore database from backup
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	// Truncate revision history
	Truncate(context.Context, *TruncateRequest) (*TruncateResponse, error)
	// Get server statistics
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Vector/semantic search using embeddings
	VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error)
	// Reindex embeddings for a collection
	VectorReindex(context.Context, *VectorReindexRequest) (*VectorReindexResponse, error)
	// Get vector/embedding statistics
	VectorStats(context.Context, *VectorStatsRequest) (*VectorStatsResponse, error)
	// Import document from URL
	ImportURL(context.Context, *ImportURLRequest) (*Document, error)
	// Set TTL on a document
	SetTTL(context.Context, *SetTTLRequest) (*Document, error)
	// Full-text search
	FTS(context.Context, *FTSRequest) (*FTSResponse, error)
	// Hybrid search (combines FTS + vector search)
	HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error)
	// Register a webhook
	RegisterWebhook(context.Context, *RegisterWebhookRequest) (*WebhookProto, error)
	// List webhooks
	ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error)
	// Delete a webhook
	DeleteWebhook(context.Context, *DeleteWebhookRequest) (*DeleteWebhookResponse, error)
	// Set JSON Schema for a collection's metadata validation
	SetSchema(context.Context, *SetSchemaRequest) (*SetSchemaResponse, error)
	// Get JSON Schema for a collection
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	// Delete JSON Schema for a collection (disables validation)
	DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error)
	// List all collection schemas
	ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
	// Validate document metadata against collection schema
	ValidateDocument(context.Context, *ValidateDocumentRequest) (*ValidateDocumentResponse, error)
	// Partial document update (meta and/or content independently)
	UpdateDocument(context.Context, *UpdateDocumentRequest) (*Document, error)
	// Get document metadata only (without content)
	GetDocumentMeta(context.Context, *GetDocumentMetaRequest) (*GetDocumentMetaResponse, error)
	// Zero-shot document classification using embedding similarity
	Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	mustEmbedUnimplementedMDDBServer()
}

// UnimplementedMDDBServer must be embedded to have forward compatible implementations.
type UnimplementedMDDBServer struct {
}

func (UnimplementedMDDBServer) Add(context.Context, *AddRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedMDDBServer) AddBatch(context.Context, *AddBatchRequest) (*AddBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBatch not implemented")
}
func (UnimplementedMDDBServer) DeleteBatch(context.Context, *DeleteBatchRequest) (*DeleteBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBatch not implemented")
}
func (UnimplementedMDDBServer) UpdateBatch(context.Context, *UpdateBatchRequest) (*UpdateBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBatch not implemented")
}
func (UnimplementedMDDBServer) Get(context.Context, *GetRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMDDBServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMDDBServer) Export(*ExportRequest, MDDB_ExportServer) error {
	return status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedMDDBServer) Backup(context.Context, *BackupRequest) (*BackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedMDDBServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedMDDBServer) Truncate(context.Context, *TruncateRequest) (*TruncateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Truncate not implemented")
}
func (UnimplementedMDDBServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedMDDBServer) VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VectorSearch not implemented")
}
func (UnimplementedMDDBServer) VectorReindex(context.Context, *VectorReindexRequest) (*VectorReindexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VectorReindex not implemented")
}
func (UnimplementedMDDBServer) VectorStats(context.Context, *VectorStatsRequest) (*VectorStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VectorStats not implemented")
}
func (UnimplementedMDDBServer) ImportURL(context.Context, *ImportURLRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportURL not implemented")
}
func (UnimplementedMDDBServer) SetTTL(context.Context, *SetTTLRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTTL not implemented")
}
func (UnimplementedMDDBServer) FTS(context.Context, *FTSRequest) (*FTSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FTS not implemented")
}
func (UnimplementedMDDBServer) HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HybridSearch not implemented")
}
func (UnimplementedMDDBServer) RegisterWebhook(context.Context, *RegisterWebhookRequest) (*WebhookProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWebhook not implemented")
}
func (UnimplementedMDDBServer) ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWebhooks not implemented")
}
func (UnimplementedMDDBServer) DeleteWebhook(context.Context, *DeleteWebhookRequest) (*DeleteWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWebhook not implemented")
}
func (UnimplementedMDDBServer) SetSchema(context.Context, *SetSchemaRequest) (*SetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSchema not implemented")
}
func (UnimplementedMDDBServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedMDDBServer) DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSchema not implemented")
}
func (UnimplementedMDDBServer) ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSchemas not implemented")
}
func (UnimplementedMDDBServer) ValidateDocument(context.Context, *ValidateDocumentRequest) (*ValidateDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateDocument not implemented")
}
func (UnimplementedMDDBServer) UpdateDocument(context.Context, *UpdateDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocument not implemented")
}
func (UnimplementedMDDBServer) GetDocumentMeta(context.Context, *GetDocumentMetaRequest) (*GetDocumentMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentMeta not implemented")
}
func (UnimplementedMDDBServer) Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedMDDBServer) mustEmbedUnimplementedMDDBServer() {}

// UnsafeMDDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MDDBServer will
// result in compilation errors.
type UnsafeMDDBServer interface {
	mustEmbedUnimplementedMDDBServer()
}

func RegisterMDDBServer(s grpc.ServiceRegistrar, srv MDDBServer) {
	s.RegisterService(&MDDB_ServiceDesc, srv)
}

func _MDDB_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_AddBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).AddBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/AddBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).AddBatch(ctx, req.(*AddBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_DeleteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).DeleteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/DeleteBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).DeleteBatch(ctx, req.(*DeleteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_UpdateBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).UpdateBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/UpdateBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).UpdateBatch(ctx, req.(*UpdateBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MDDBServer).Export(m, &mDDBExportServer{stream})
}

type MDDB_ExportServer interface {
	Send(*ExportChunk) error
	grpc.ServerStream
}

type mDDBExportServer struct {
	grpc.ServerStream
}

func (x *mDDBExportServer) Send(m *ExportChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _MDDB_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/Backup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Truncate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruncateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Truncate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/Truncate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Truncate(ctx, req.(*TruncateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_VectorSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).VectorSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/VectorSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).VectorSearch(ctx, req.(*VectorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_VectorReindex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorReindexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).VectorReindex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/VectorReindex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).VectorReindex(ctx, req.(*VectorReindexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_VectorStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).VectorStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/VectorStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).VectorStats(ctx, req.(*VectorStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_ImportURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).ImportURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/ImportURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).ImportURL(ctx, req.(*ImportURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_SetTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).SetTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/SetTTL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).SetTTL(ctx, req.(*SetTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_FTS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FTSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).FTS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/FTS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).FTS(ctx, req.(*FTSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_HybridSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HybridSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).HybridSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/HybridSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).HybridSearch(ctx, req.(*HybridSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_RegisterWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).RegisterWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/RegisterWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).RegisterWebhook(ctx, req.(*RegisterWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_ListWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).ListWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/ListWebhooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).ListWebhooks(ctx, req.(*ListWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_DeleteWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).DeleteWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/DeleteWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).DeleteWebhook(ctx, req.(*DeleteWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_SetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).SetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/SetSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).SetSchema(ctx, req.(*SetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/GetSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_DeleteSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).DeleteSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/DeleteSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).DeleteSchema(ctx, req.(*DeleteSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).ListSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/ListSchemas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).ListSchemas(ctx, req.(*ListSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_ValidateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).ValidateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/ValidateDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).ValidateDocument(ctx, req.(*ValidateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_UpdateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).UpdateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/UpdateDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).UpdateDocument(ctx, req.(*UpdateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_GetDocumentMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).GetDocumentMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/GetDocumentMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).GetDocumentMeta(ctx, req.(*GetDocumentMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDB_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDB/Classify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MDDB_ServiceDesc is the grpc.ServiceDesc for MDDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MDDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mddb.MDDB",
	HandlerType: (*MDDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _MDDB_Add_Handler,
		},
		{
			MethodName: "AddBatch",
			Handler:    _MDDB_AddBatch_Handler,
		},
		{
			MethodName: "DeleteBatch",
			Handler:    _MDDB_DeleteBatch_Handler,
		},
		{
			MethodName: "UpdateBatch",
			Handler:    _MDDB_UpdateBatch_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MDDB_Get_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _MDDB_Search_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _MDDB_Backup_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _MDDB_Restore_Handler,
		},
		{
			MethodName: "Truncate",
			Handler:    _MDDB_Truncate_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _MDDB_Stats_Handler,
		},
		{
			MethodName: "VectorSearch",
			Handler:    _MDDB_VectorSearch_Handler,
		},
		{
			MethodName: "VectorReindex",
			Handler:    _MDDB_VectorReindex_Handler,
		},
		{
			MethodName: "VectorStats",
			Handler:    _MDDB_VectorStats_Handler,
		},
		{
			MethodName: "ImportURL",
			Handler:    _MDDB_ImportURL_Handler,
		},
		{
			MethodName: "SetTTL",
			Handler:    _MDDB_SetTTL_Handler,
		},
		{
			MethodName: "FTS",
			Handler:    _MDDB_FTS_Handler,
		},
		{
			MethodName: "HybridSearch",
			Handler:    _MDDB_HybridSearch_Handler,
		},
		{
			MethodName: "RegisterWebhook",
			Handler:    _MDDB_RegisterWebhook_Handler,
		},
		{
			MethodName: "ListWebhooks",
			Handler:    _MDDB_ListWebhooks_Handler,
		},
		{
			MethodName: "DeleteWebhook",
			Handler:    _MDDB_DeleteWebhook_Handler,
		},
		{
			MethodName: "SetSchema",
			Handler:    _MDDB_SetSchema_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _MDDB_GetSchema_Handler,
		},
		{
			MethodName: "DeleteSchema",
			Handler:    _MDDB_DeleteSchema_Handler,
		},
		{
			MethodName: "ListSchemas",
			Handler:    _MDDB_ListSchemas_Handler,
		},
		{
			MethodName: "ValidateDocument",
			Handler:    _MDDB_ValidateDocument_Handler,
		},
		{
			MethodName: "UpdateDocument",
			Handler:    _MDDB_UpdateDocument_Handler,
		},
		{
			MethodName: "GetDocumentMeta",
			Handler:    _MDDB_GetDocumentMeta_Handler,
		},
		{
			MethodName: "Classify",
			Handler:    _MDDB_Classify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Export",
			Handler:       _MDDB_Export_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/mddb/proto/mddb.proto",
}

// MDDBReplicationClient is the client API for MDDBReplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MDDBReplicationClient interface {
	// RequestSnapshot streams a full database snapshot to a follower
	RequestSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (MDDBReplication_RequestSnapshotClient, error)
	// StreamBinlog streams binlog entries from a given LSN (long-lived server-stream)
	StreamBinlog(ctx context.Context, in *StreamBinlogRequest, opts ...grpc.CallOption) (MDDBReplication_StreamBinlogClient, error)
	// ReplicationStatus returns the current replication state of this node
	ReplicationStatus(ctx context.Context, in *ReplicationStatusRequest, opts ...grpc.CallOption) (*ReplicationStatusResponse, error)
	// AcknowledgeLSN allows a follower to confirm it has applied up to a given LSN
	AcknowledgeLSN(ctx context.Context, in *AcknowledgeLSNRequest, opts ...grpc.CallOption) (*AcknowledgeLSNResponse, error)
}

type mDDBReplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewMDDBReplicationClient(cc grpc.ClientConnInterface) MDDBReplicationClient {
	return &mDDBReplicationClient{cc}
}

func (c *mDDBReplicationClient) RequestSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (MDDBReplication_RequestSnapshotClient, error) {
	stream, err := c.cc.NewStream(ctx, &MDDBReplication_ServiceDesc.Streams[0], "/mddb.MDDBReplication/RequestSnapshot", opts...)
	if err != nil {
		return nil, err
	}
	x := &mDDBReplicationRequestSnapshotClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MDDBReplication_RequestSnapshotClient interface {
	Recv() (*SnapshotChunk, error)
	grpc.ClientStream
}

type mDDBReplicationRequestSnapshotClient struct {
	grpc.ClientStream
}

func (x *mDDBReplicationRequestSnapshotClient) Recv() (*SnapshotChunk, error) {
	m := new(SnapshotChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mDDBReplicationClient) StreamBinlog(ctx context.Context, in *StreamBinlogRequest, opts ...grpc.CallOption) (MDDBReplication_StreamBinlogClient, error) {
	stream, err := c.cc.NewStream(ctx, &MDDBReplication_ServiceDesc.Streams[1], "/mddb.MDDBReplication/StreamBinlog", opts...)
	if err != nil {
		return nil, err
	}
	x := &mDDBReplicationStreamBinlogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MDDBReplication_StreamBinlogClient interface {
	Recv() (*BinlogEntryProto, error)
	grpc.ClientStream
}

type mDDBReplicationStreamBinlogClient struct {
	grpc.ClientStream
}

func (x *mDDBReplicationStreamBinlogClient) Recv() (*BinlogEntryProto, error) {
	m := new(BinlogEntryProto)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mDDBReplicationClient) ReplicationStatus(ctx context.Context, in *ReplicationStatusRequest, opts ...grpc.CallOption) (*ReplicationStatusResponse, error) {
	out := new(ReplicationStatusResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDBReplication/ReplicationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mDDBReplicationClient) AcknowledgeLSN(ctx context.Context, in *AcknowledgeLSNRequest, opts ...grpc.CallOption) (*AcknowledgeLSNResponse, error) {
	out := new(AcknowledgeLSNResponse)
	err := c.cc.Invoke(ctx, "/mddb.MDDBReplication/AcknowledgeLSN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MDDBReplicationServer is the server API for MDDBReplication service.
// All implementations must embed UnimplementedMDDBReplicationServer
// for forward compatibility
type MDDBReplicationServer interface {
	// RequestSnapshot streams a full database snapshot to a follower
	RequestSnapshot(*SnapshotRequest, MDDBReplication_RequestSnapshotServer) error
	// StreamBinlog streams binlog entries from a given LSN (long-lived server-stream)
	StreamBinlog(*StreamBinlogRequest, MDDBReplication_StreamBinlogServer) error
	// ReplicationStatus returns the current replication state of this node
	ReplicationStatus(context.Context, *ReplicationStatusRequest) (*ReplicationStatusResponse, error)
	// AcknowledgeLSN allows a follower to confirm it has applied up to a given LSN
	AcknowledgeLSN(context.Context, *AcknowledgeLSNRequest) (*AcknowledgeLSNResponse, error)
	mustEmbedUnimplementedMDDBReplicationServer()
}

// UnimplementedMDDBReplicationServer must be embedded to have forward compatible implementations.
type UnimplementedMDDBReplicationServer struct {
}

func (UnimplementedMDDBReplicationServer) RequestSnapshot(*SnapshotRequest, MDDBReplication_RequestSnapshotServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestSnapshot not implemented")
}
func (UnimplementedMDDBReplicationServer) StreamBinlog(*StreamBinlogRequest, MDDBReplication_StreamBinlogServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamBinlog not implemented")
}
func (UnimplementedMDDBReplicationServer) ReplicationStatus(context.Context, *ReplicationStatusRequest) (*ReplicationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicationStatus not implemented")
}
func (UnimplementedMDDBReplicationServer) AcknowledgeLSN(context.Context, *AcknowledgeLSNRequest) (*AcknowledgeLSNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeLSN not implemented")
}
func (UnimplementedMDDBReplicationServer) mustEmbedUnimplementedMDDBReplicationServer() {}

// UnsafeMDDBReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MDDBReplicationServer will
// result in compilation errors.
type UnsafeMDDBReplicationServer interface {
	mustEmbedUnimplementedMDDBReplicationServer()
}

func RegisterMDDBReplicationServer(s grpc.ServiceRegistrar, srv MDDBReplicationServer) {
	s.RegisterService(&MDDBReplication_ServiceDesc, srv)
}

func _MDDBReplication_RequestSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MDDBReplicationServer).RequestSnapshot(m, &mDDBReplicationRequestSnapshotServer{stream})
}

type MDDBReplication_RequestSnapshotServer interface {
	Send(*SnapshotChunk) error
	grpc.ServerStream
}

type mDDBReplicationRequestSnapshotServer struct {
	grpc.ServerStream
}

func (x *mDDBReplicationRequestSnapshotServer) Send(m *SnapshotChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _MDDBReplication_StreamBinlog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBinlogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MDDBReplicationServer).StreamBinlog(m, &mDDBReplicationStreamBinlogServer{stream})
}

type MDDBReplication_StreamBinlogServer interface {
	Send(*BinlogEntryProto) error
	grpc.ServerStream
}

type mDDBReplicationStreamBinlogServer struct {
	grpc.ServerStream
}

func (x *mDDBReplicationStreamBinlogServer) Send(m *BinlogEntryProto) error {
	return x.ServerStream.SendMsg(m)
}

func _MDDBReplication_ReplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBReplicationServer).ReplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDBReplication/ReplicationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBReplicationServer).ReplicationStatus(ctx, req.(*ReplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MDDBReplication_AcknowledgeLSN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeLSNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDDBReplicationServer).AcknowledgeLSN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mddb.MDDBReplication/AcknowledgeLSN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDDBReplicationServer).AcknowledgeLSN(ctx, req.(*AcknowledgeLSNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MDDBReplication_ServiceDesc is the grpc.ServiceDesc for MDDBReplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MDDBReplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mddb.MDDBReplication",
	HandlerType: (*MDDBReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplicationStatus",
			Handler:    _MDDBReplication_ReplicationStatus_Handler,
		},
		{
			MethodName: "AcknowledgeLSN",
			Handler:    _MDDBReplication_AcknowledgeLSN_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestSnapshot",
			Handler:       _MDDBReplication_RequestSnapshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBinlog",
			Handler:       _MDDBReplication_StreamBinlog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/mddb/proto/mddb.proto",
}
