package main

// `ssg init` scaffolds a ready-to-build project in the current directory —
// config, a content source tree with a sample page and post, and a static
// folder — WITHOUT overwriting any existing file. Every file that already
// exists is left untouched and reported as skipped, so running it in a
// populated directory is safe (idempotent).

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// scaffoldFile is one file init writes, keyed by its relative path.
type scaffoldFile struct {
	path    string
	content string
}

// runInit scaffolds the starter project. An optional positional argument sets
// the content source name (default "site"); --domain overrides the domain.
func runInit(args []string) int {
	source := "site"
	domain := "example.com"
	for i := 0; i < len(args); i++ {
		switch {
		case args[i] == "--domain" && i+1 < len(args):
			domain = args[i+1]
			i++
		case strings.HasPrefix(args[i], "--domain="):
			domain = strings.TrimPrefix(args[i], "--domain=")
		case strings.HasPrefix(args[i], "-"):
			fmt.Fprintf(os.Stderr, "❌ unknown flag %q\n\nusage: ssg init [source-name] [--domain example.com]\n", args[i])
			return 2
		default:
			source = args[i]
		}
	}
	if strings.ContainsAny(source, "/\\") || strings.Contains(source, "..") {
		fmt.Fprintf(os.Stderr, "❌ invalid source name %q\n", source)
		return 1
	}

	files := initScaffold(source, domain)
	created, skipped, err := writeScaffold(files)
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ %v\n", err)
		return 1
	}
	for _, f := range created {
		fmt.Printf("   ✅ created %s\n", f)
	}
	for _, f := range skipped {
		fmt.Printf("   ⏭️  kept existing %s\n", f)
	}
	fmt.Printf("\n✨ Project ready. Build it with:\n   ssg --config .ssg.yaml --http --watch\n")
	return 0
}

// writeScaffold writes each file that does not already exist, creating parent
// directories. Returns the created and skipped relative paths.
func writeScaffold(files []scaffoldFile) (created, skipped []string, err error) {
	for _, f := range files {
		if _, statErr := os.Stat(f.path); statErr == nil {
			skipped = append(skipped, f.path)
			continue
		}
		// #nosec G301 -- scaffolded project directories are world-traversable
		if mkErr := os.MkdirAll(filepath.Dir(f.path), 0o755); mkErr != nil {
			return created, skipped, mkErr
		}
		// #nosec G306 -- scaffolded project files are world-readable
		if wErr := os.WriteFile(f.path, []byte(f.content), 0o644); wErr != nil {
			return created, skipped, wErr
		}
		created = append(created, f.path)
	}
	return created, skipped, nil
}

// initScaffold returns the starter file set for the given source and domain.
func initScaffold(source, domain string) []scaffoldFile {
	base := filepath.Join("content", source)
	return []scaffoldFile{
		{".ssg.yaml", initConfigYAML(source, domain)},
		{filepath.Join(base, "metadata.json"), initMetadataJSON(domain)},
		{filepath.Join(base, "pages", "index.md"), initIndexPage()},
		{filepath.Join(base, "posts", "hello-world.md"), initHelloPost()},
		{filepath.Join("static", ".gitkeep"), ""},
		{".gitignore", initGitignore()},
	}
}

func initConfigYAML(source, domain string) string {
	return fmt.Sprintf(`# Generated by `+"`ssg init`"+`. See docs/CONFIGURATION.md for every key.
source: %s
template: simple
domain: %s

content_dir: content
output_dir: output
static_dir: static

feed: true
search_index: true
seo: true
`, source, domain)
}

func initMetadataJSON(domain string) string {
	return fmt.Sprintf(`{
  "title": "My Site",
  "description": "A site built with SSG.",
  "url": "https://%s",
  "language": "en",
  "categories": [
    { "id": 1, "name": "General", "slug": "general", "count": 1 }
  ],
  "users": [
    { "id": 1, "name": "Author", "slug": "author" }
  ],
  "media": []
}
`, domain)
}

func initIndexPage() string {
	return `---
title: "Home"
slug: "home"
date: "2026-01-01T00:00:00Z"
description: "Welcome to a site built with SSG."
status: "publish"
type: "page"
---

# Welcome

This page was scaffolded by ` + "`ssg init`" + `. Edit it in
` + "`content/<source>/pages/index.md`" + ` and rebuild.
`
}

func initHelloPost() string {
	return `---
title: "Hello, World"
slug: "hello-world"
date: "2026-01-01T12:00:00Z"
description: "The first post on a fresh SSG site."
status: "publish"
type: "post"
categories:
  - 1
---

# Hello, World

Your first post. Add more under ` + "`content/<source>/posts/`" + `.
`
}

func initGitignore() string {
	return `output/
.ssg-cache/
*.zip
*.tar.gz
*.tar.xz
`
}
