package main

// The preview serves the `_headers` it generates (#181).

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spagu/ssg/internal/config"
)

// publishHeaderText parses text and mounts the handler over a stand-in server.
func publishHeaderText(t *testing.T, text string) (http.Handler, []string) {
	t.Helper()
	var warnings []string
	table := parseHeadersFile(text, quietWarn(&warnings))
	liveHeaders.Store(&table)
	return liveHeadersHandler(staticSaying("static")), warnings
}

// defaultHeadersFile is what the generator writes with no `headers:` config —
// the shape the matcher actually has to cope with, not an invented one.
const defaultHeadersFile = `# Cloudflare Pages Headers
# Generated by SSG

# Security headers for all pages
/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin

# Cache static assets for 1 year
/css/*
  Cache-Control: public, max-age=31536000, immutable

# Cache HTML pages for 1 hour
/*.html
  Cache-Control: public, max-age=3600
/
  Cache-Control: public, max-age=3600
`

// TestAPatternAddsItsHeaders: the plain case, on the file the build writes.
func TestAPatternAddsItsHeaders(t *testing.T) {
	resetLiveRules(t)
	h, warnings := publishHeaderText(t, defaultHeadersFile)
	if len(warnings) != 0 {
		t.Fatalf("the generator's own format must parse cleanly: %v", warnings)
	}

	rec := getPath(h, "/css/site.css")
	if got := rec.Header().Get("Cache-Control"); got != "public, max-age=31536000, immutable" {
		t.Errorf("Cache-Control = %q", got)
	}
	if got := rec.Header().Get("X-Content-Type-Options"); got != "nosniff" {
		t.Errorf("the /* block must apply too: %q", got)
	}
}

// TestASuffixGlobMatches: `/*.html` is a wildcard in the middle of a pattern,
// which a naive prefix matcher gets wrong.
func TestASuffixGlobMatches(t *testing.T) {
	resetLiveRules(t)
	h, _ := publishHeaderText(t, defaultHeadersFile)

	if got := getPath(h, "/about.html").Header().Get("Cache-Control"); got != "public, max-age=3600" {
		t.Errorf("/about.html Cache-Control = %q", got)
	}
	// A directory URL is not an .html path and must not pick that block up.
	if got := getPath(h, "/about/").Header().Get("Cache-Control"); got != "" {
		t.Errorf("/about/ Cache-Control = %q, want none from the file", got)
	}
	// The bare `/` block is exact, so it applies to the root and nowhere else.
	if got := getPath(h, "/").Header().Get("Cache-Control"); got != "public, max-age=3600" {
		t.Errorf("root Cache-Control = %q", got)
	}
}

// TestTheFirstMatchingValueWins: Cloudflare applies the first matching value per
// header name, which is why block order in the generated file is deliberate.
func TestTheFirstMatchingValueWins(t *testing.T) {
	resetLiveRules(t)
	h, _ := publishHeaderText(t, "/css/*\n  Cache-Control: first\n/*\n  Cache-Control: second\n")
	if got := getPath(h, "/css/a.css").Header().Get("Cache-Control"); got != "first" {
		t.Errorf("Cache-Control = %q, want the earlier block's value", got)
	}
}

// TestTheFileWinsOverTheBuiltInSecurityHeaders: what the deployed platform
// would serve is the whole point of a preview that reads this file.
func TestTheFileWinsOverTheBuiltInSecurityHeaders(t *testing.T) {
	resetLiveRules(t)
	table := parseHeadersFile("/*\n  X-Frame-Options: DENY\n", func(string, ...any) {})
	liveHeaders.Store(&table)

	// The real chain: the middleware sets SAMEORIGIN, the file then says DENY.
	h := securityHeadersMiddleware(liveHeadersHandler(staticSaying("static")), false)
	rec := getPath(h, "/anything")
	if got := rec.Header().Get("X-Frame-Options"); got != "DENY" {
		t.Errorf("X-Frame-Options = %q, want the file's value", got)
	}
	// A header the file does not mention keeps the built-in value.
	if got := rec.Header().Get("X-Content-Type-Options"); got != "nosniff" {
		t.Errorf("X-Content-Type-Options = %q", got)
	}
}

// TestANonMatchingPathIsUntouched: nothing is added where nothing matches.
func TestANonMatchingPathIsUntouched(t *testing.T) {
	resetLiveRules(t)
	h, _ := publishHeaderText(t, "/css/*\n  Cache-Control: cached\n")
	rec := getPath(h, "/index.html")
	if got := rec.Header().Get("Cache-Control"); got != "" {
		t.Errorf("Cache-Control = %q, want none", got)
	}
	if rec.Body.String() != "static" {
		t.Errorf("the response must still be served: %q", rec.Body)
	}
}

// TestAMalformedHeaderLineIsSkipped: a file the build wrote must never take the
// server down, and a warning must name the line so it can be found.
func TestAMalformedHeaderLineIsSkipped(t *testing.T) {
	resetLiveRules(t)
	h, warnings := publishHeaderText(t, strings.Join([]string{
		"  Orphan: before any pattern",
		"/*",
		"  no-colon-here",
		"  : empty name",
		"  X-Kept: yes",
	}, "\n"))

	if len(warnings) != 3 {
		t.Fatalf("want three warnings, got %d: %v", len(warnings), warnings)
	}
	for _, w := range warnings {
		if !strings.Contains(w, "_headers:") {
			t.Errorf("a warning must name the line: %q", w)
		}
	}
	if got := getPath(h, "/x").Header().Get("X-Kept"); got != "yes" {
		t.Errorf("the good line must survive: %q", got)
	}
}

// TestNoHeaderTableMeansPureFallThrough: safe from the moment it is built.
func TestNoHeaderTableMeansPureFallThrough(t *testing.T) {
	resetLiveRules(t)
	h := liveHeadersHandler(staticSaying("static"))
	if rec := getPath(h, "/anything"); rec.Body.String() != "static" {
		t.Errorf("body = %q", rec.Body)
	}
}

// TestTheHeaderTableSwapIsAtomic: a request sees one whole table or the other.
func TestTheHeaderTableSwapIsAtomic(t *testing.T) {
	resetLiveRules(t)
	h := liveHeadersHandler(staticSaying("static"))
	first := parseHeadersFile("/*\n  X-Table: a\n", func(string, ...any) {})
	liveHeaders.Store(&first)

	done := make(chan struct{})
	go func() {
		defer close(done)
		for i := 0; i < 200; i++ {
			value := "a"
			if i%2 == 0 {
				value = "b"
			}
			table := parseHeadersFile("/*\n  X-Table: "+value+"\n", func(string, ...any) {})
			liveHeaders.Store(&table)
		}
	}()
	for i := 0; i < 200; i++ {
		if got := getPath(h, "/x").Header().Get("X-Table"); got != "a" && got != "b" {
			t.Fatalf("X-Table = %q during a swap", got)
		}
	}
	<-done
}

// TestBothTablesAreRepublishedTogether: the two files change on every build, so
// one entry point re-reads both.
func TestBothTablesAreRepublishedTogether(t *testing.T) {
	resetLiveRules(t)
	dir := t.TempDir()
	write := func(name, body string) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	write("_redirects", "/old /new 301\n")
	write("_headers", "/*\n  X-Build: one\n")

	cfg := config.DefaultConfig()
	cfg.Quiet = true
	cfg.OutputDir = dir
	republishOutputRules(cfg)

	redirects := liveRedirectHandler(staticSaying("static"))
	headers := liveHeadersHandler(staticSaying("static"))
	if got := getPath(redirects, "/old").Header().Get("Location"); got != "/new" {
		t.Errorf("Location = %q", got)
	}
	if got := getPath(headers, "/x").Header().Get("X-Build"); got != "one" {
		t.Errorf("X-Build = %q", got)
	}

	// A rebuild rewrites both; the next request must see the new pair.
	write("_redirects", "/old /newer 301\n")
	write("_headers", "/*\n  X-Build: two\n")
	republishOutputRules(cfg)
	if got := getPath(redirects, "/old").Header().Get("Location"); got != "/newer" {
		t.Errorf("after the rebuild Location = %q", got)
	}
	if got := getPath(headers, "/x").Header().Get("X-Build"); got != "two" {
		t.Errorf("after the rebuild X-Build = %q", got)
	}
}

// TestTheServerChainOrdersEndpointsRedirectsHeadersStatic pins the order the
// whole feature rests on, through the handler the server actually builds.
func TestTheServerChainOrdersEndpointsRedirectsHeadersStatic(t *testing.T) {
	resetLiveRules(t)
	resetLiveEndpoints(t)
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "index.html"), []byte("<html></html>"), 0o600); err != nil {
		t.Fatal(err)
	}
	for name, body := range map[string]string{
		"_redirects": "/gone-away/ /moved/ 301\n",
		"_headers":   "/*\n  X-From-File: yes\n",
	} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	cfg := config.DefaultConfig()
	cfg.Quiet = true
	cfg.OutputDir = dir
	cfg.Endpoints = []config.Endpoint{{Path: "/api/ping", Type: "redirect", To: "/pong/"}}
	h := buildServerHandler(cfg, false)

	// An endpoint answers before any file rule.
	if got := getPath(h, "/api/ping").Header().Get("Location"); got != "/pong/" {
		t.Errorf("endpoint Location = %q", got)
	}
	// A file redirect answers before the static tree.
	if got := getPath(h, "/gone-away/").Header().Get("Location"); got != "/moved/" {
		t.Errorf("redirect Location = %q", got)
	}
	// And a served asset carries the file's headers.
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/", nil))
	if got := rec.Header().Get("X-From-File"); got != "yes" {
		t.Errorf("X-From-File = %q on the served page", got)
	}
}

// TestAPatternWithSeveralWildcardsMatches: `headers:` takes any pattern the
// operator writes, not only the shapes the defaults use, so the matcher has to
// cope with a wildcard that is neither first nor last.
func TestAPatternWithSeveralWildcardsMatches(t *testing.T) {
	resetLiveRules(t)
	h, _ := publishHeaderText(t, "/assets/*/dist/*.js\n  X-Bundle: yes\n")

	if got := getPath(h, "/assets/app/dist/main.js").Header().Get("X-Bundle"); got != "yes" {
		t.Errorf("X-Bundle = %q, want the block to apply", got)
	}
	// The middle literal has to be there, and the suffix has to match.
	for _, miss := range []string{"/assets/app/build/main.js", "/assets/app/dist/main.css", "/other/app/dist/main.js"} {
		if got := getPath(h, miss).Header().Get("X-Bundle"); got != "" {
			t.Errorf("%s picked the block up: %q", miss, got)
		}
	}
}
