package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// exportMetadata is the shape wpexporter writes: what the site calls itself,
// plus the palette its theme declared.
const exportMetadata = `{
  "site": {"name": "Magna Valor", "description": "Supply Chain Global Advisory",
           "url": "https://magnavalor.eu", "timezone": "Europe/Warsaw"},
  "marketing": {"og_site_name": "Magna Valor",
                "colors": {"primary": "#7b2ff7", "text": "#111111"}}
}`

// writeMigrateFixture lays out a project with a scaffolded config and an
// export, and chdirs into it. Returns the config path.
func writeMigrateFixture(t *testing.T, cfgBody, metadata string) (cfgPath, dest string) {
	t.Helper()
	tmp := chdirTemp(t)
	cfgPath = filepath.Join(tmp, ".ssg.yaml")
	if err := os.WriteFile(cfgPath, []byte(cfgBody), 0o644); err != nil {
		t.Fatal(err)
	}
	dest = filepath.Join(tmp, "content", "magnavalor.eu")
	if err := os.MkdirAll(dest, 0o755); err != nil {
		t.Fatal(err)
	}
	if metadata != "" {
		if err := os.WriteFile(filepath.Join(dest, "metadata.json"), []byte(metadata), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return cfgPath, dest
}

func TestApplyMigratedIdentity_FillsEmptyKeys(t *testing.T) {
	cfgPath, dest := writeMigrateFixture(t,
		"# Generated by `ssg init`.\nsource: magnavalor.eu\ndomain: magnavalor.eu\n", exportMetadata)

	applied := applyMigratedIdentity(cfgPath, dest)

	if len(applied) != 4 {
		t.Fatalf("expected 4 keys filled in, got %v", applied)
	}
	out, _ := os.ReadFile(cfgPath)
	for _, want := range []string{
		"title: Magna Valor",
		"description: Supply Chain Global Advisory",
		"timezone: Europe/Warsaw",
		"primary: '#7b2ff7'",
	} {
		if !strings.Contains(string(out), want) {
			t.Errorf("expected %q in the config:\n%s", want, out)
		}
	}
	// The file is edited as a document: its comment and existing keys survive.
	if !strings.Contains(string(out), "# Generated by `ssg init`.") {
		t.Errorf("the config comment was lost:\n%s", out)
	}
	if !strings.Contains(string(out), "source: magnavalor.eu") {
		t.Errorf("existing keys were lost:\n%s", out)
	}
}

func TestApplyMigratedIdentity_NeverOverwrites(t *testing.T) {
	cfgPath, dest := writeMigrateFixture(t,
		"source: magnavalor.eu\ntitle: My Own Title\ncolors:\n  primary: \"#000000\"\n", exportMetadata)

	applied := applyMigratedIdentity(cfgPath, dest)

	out, _ := os.ReadFile(cfgPath)
	if !strings.Contains(string(out), "title: My Own Title") {
		t.Errorf("an author's title must never be replaced:\n%s", out)
	}
	if strings.Contains(string(out), "#7b2ff7") {
		t.Errorf("an author's palette must never be replaced:\n%s", out)
	}
	for _, line := range applied {
		if strings.HasPrefix(line, "title:") || strings.HasPrefix(line, "colors:") {
			t.Errorf("reported a key it must not have set: %q", line)
		}
	}
	// The keys it CAN fill in are still filled in.
	if !strings.Contains(string(out), "description: Supply Chain Global Advisory") {
		t.Errorf("description should have been added:\n%s", out)
	}
}

func TestApplyMigratedIdentity_NoMetadataIsNotAnError(t *testing.T) {
	cfgPath, dest := writeMigrateFixture(t, "source: site\n", "")

	if applied := applyMigratedIdentity(cfgPath, dest); applied != nil {
		t.Errorf("a missing metadata.json should change nothing, got %v", applied)
	}
	if applied := applyMigratedIdentity("", dest); applied != nil {
		t.Errorf("no config file should change nothing, got %v", applied)
	}

	// Unreadable JSON is equally harmless.
	if err := os.WriteFile(filepath.Join(dest, "metadata.json"), []byte("{not json"), 0o644); err != nil {
		t.Fatal(err)
	}
	if applied := applyMigratedIdentity(cfgPath, dest); applied != nil {
		t.Errorf("broken metadata should change nothing, got %v", applied)
	}
}

func TestApplyMigratedIdentity_MissingConfigFile(t *testing.T) {
	_, dest := writeMigrateFixture(t, "source: site\n", exportMetadata)
	if applied := applyMigratedIdentity(filepath.Join(dest, "absent.yaml"), dest); applied != nil {
		t.Errorf("an unreadable config should change nothing, got %v", applied)
	}
}

func TestApplyMigratedIdentity_EmptyExportSetsNothing(t *testing.T) {
	cfgPath, dest := writeMigrateFixture(t, "source: site\n", `{"site":{},"marketing":{}}`)
	if applied := applyMigratedIdentity(cfgPath, dest); applied != nil {
		t.Errorf("an export with no identity should set nothing, got %v", applied)
	}
}

func TestIANATimezone(t *testing.T) {
	cases := map[string]string{
		"Europe/Warsaw":   "Europe/Warsaw",
		"UTC":             "UTC",
		"UTC+0":           "UTC",
		"utc-0":           "UTC",
		"  Europe/Rome  ": "Europe/Rome",
		// A bare offset is not a zone: it carries no DST rules, so it is dropped
		// rather than written as something that will not load.
		"UTC+5.5": "",
		"UTC-3":   "",
		"":        "",
	}
	for in, want := range cases {
		if got := ianaTimezone(in); got != want {
			t.Errorf("ianaTimezone(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestDescribeConfigValue(t *testing.T) {
	if got := describeConfigValue("Magna Valor"); got != "Magna Valor" {
		t.Errorf("scalar should render as itself, got %q", got)
	}
	if got := describeConfigValue(map[string]string{"a": "#fff", "b": "#000"}); !strings.Contains(got, "2 colour(s)") {
		t.Errorf("a palette should render as a count, got %q", got)
	}
}

func TestPrintMigratedIdentity_SilentWhenNothingApplied(t *testing.T) {
	// Nothing to say must print nothing: a migration that changed no config key
	// should not imply that it did.
	chdirTemp(t)
	printMigratedIdentity(nil)
}
