package endpoints

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spagu/ssg/internal/config"
)

func init() { Register(cloudflareAdapter{}) }

// cloudflareAdapter emits Cloudflare Pages Functions: dependency-free ES modules
// under functions/, the same tree the hand-written worker integration uses, so
// declared endpoints and bespoke workers share one deployment instead of two
// parallel mechanisms (#63).
type cloudflareAdapter struct{}

func (cloudflareAdapter) Platform() string { return "cloudflare" }

// Emit writes one functions/<path>.js module per endpoint under outDir.
func (cloudflareAdapter) Emit(eps []config.Endpoint, outDir string) ([]string, error) {
	var written []string
	for _, ep := range eps {
		src, err := cloudflareSource(ep)
		if err != nil {
			return nil, fmt.Errorf("endpoint %q: %w", ep.Path, err)
		}
		rel := filepath.Join("functions", filepath.FromSlash(functionFile(ep.Path, ".js")))
		full := filepath.Join(outDir, rel)
		// #nosec G301 -- Pages Functions dirs must be traversable by the build
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return nil, err
		}
		// #nosec G306 -- function source is a public build artifact
		if err := os.WriteFile(full, []byte(src), 0o644); err != nil {
			return nil, err
		}
		written = append(written, rel)
	}
	return written, nil
}

const cfGeneratedHeader = "// Generated by SSG from endpoints: (#63). Do not edit by hand.\n"

// cloudflareSource renders the Pages Function module for one endpoint.
func cloudflareSource(ep config.Endpoint) (string, error) {
	switch ep.Type {
	case "redirect":
		if ep.To == "" {
			return "", fmt.Errorf("redirect needs a 'to'")
		}
		status := ep.Status
		if status == 0 {
			status = 302
		}
		if status < 300 || status > 399 {
			return "", fmt.Errorf("redirect status %d is not a 3xx", status)
		}
		var b strings.Builder
		b.WriteString(cfGeneratedHeader)
		b.WriteString("export function onRequest(context) {\n")
		b.WriteString("  const to = new URL(" + jsStringLit(ep.To) + ", context.request.url).toString();\n")
		fmt.Fprintf(&b, "  return Response.redirect(to, %d);\n", status)
		b.WriteString("}\n")
		return b.String(), nil
	case "proxy":
		if ep.Target == "" {
			return "", fmt.Errorf("proxy needs a 'target'")
		}
		var b strings.Builder
		b.WriteString(cfGeneratedHeader)
		b.WriteString("export async function onRequest(context) {\n")
		b.WriteString("  const { request } = context;\n")
		if m := methodsLit(ep.Methods); m != "" {
			b.WriteString("  const allowed = " + m + ";\n")
			b.WriteString("  if (!allowed.includes(request.method)) {\n")
			b.WriteString("    return new Response(\"method not allowed\", { status: 405, headers: { Allow: allowed.join(\", \") } });\n")
			b.WriteString("  }\n")
		}
		b.WriteString("  const target = new URL(" + jsStringLit(ep.Target) + ");\n")
		b.WriteString("  target.search = new URL(request.url).search;\n")
		b.WriteString("  return fetch(new Request(target, request));\n")
		b.WriteString("}\n")
		return b.String(), nil
	default:
		return "", fmt.Errorf("unknown type %q (want redirect or proxy)", ep.Type)
	}
}
