package config

import (
	"strings"
	"testing"
)

const annotatedConfig = `# Generated by ` + "`ssg init`" + `.
source: mysite     # the content collection
template: simple

feed: true
`

func TestSetYAMLKey_AppendsAndPreservesTheDocument(t *testing.T) {
	out, err := SetYAMLKey([]byte(annotatedConfig), "title", "My Site")
	if err != nil {
		t.Fatal(err)
	}
	got := string(out)

	if !strings.Contains(got, "title: My Site") {
		t.Errorf("new key missing:\n%s", got)
	}
	// The file is edited as a document, so its comments and key order survive.
	for _, want := range []string{"# Generated by", "# the content collection", "source: mysite", "template: simple"} {
		if !strings.Contains(got, want) {
			t.Errorf("expected %q to survive the edit:\n%s", want, got)
		}
	}
	if strings.Index(got, "source:") > strings.Index(got, "title:") {
		t.Errorf("existing keys should keep their order, new ones append:\n%s", got)
	}
}

func TestSetYAMLKey_ReplacesKeepingItsComments(t *testing.T) {
	out, err := SetYAMLKey([]byte(annotatedConfig), "template", "ssgtheme")
	if err != nil {
		t.Fatal(err)
	}
	got := string(out)

	if !strings.Contains(got, "template: ssgtheme") || strings.Contains(got, "template: simple") {
		t.Errorf("value not replaced:\n%s", got)
	}
	// A comment attached to the replaced key is carried over, not dropped.
	out, err = SetYAMLKey([]byte(annotatedConfig), "source", "other")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), "# the content collection") {
		t.Errorf("the key's own comment was lost:\n%s", out)
	}
}

func TestSetYAMLKey_StructuredValue(t *testing.T) {
	out, err := SetYAMLKey([]byte("source: mysite\n"), "colors", map[string]string{"primary": "#7b2ff7"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), "colors:\n  primary: '#7b2ff7'") {
		t.Errorf("map should be written at two-space indent:\n%s", out)
	}
}

func TestSetYAMLKey_RefusesWhatIsNotAMapping(t *testing.T) {
	if _, err := SetYAMLKey([]byte("- a\n- b\n"), "title", "x"); err == nil {
		t.Error("a sequence document must error")
	}
	if _, err := SetYAMLKey([]byte("{{ not yaml\n"), "title", "x"); err == nil {
		t.Error("unparseable YAML must error")
	}
	if _, err := SetYAMLKey(nil, "title", "x"); err == nil {
		t.Error("an empty document has no mapping to edit")
	}
}

func TestHasYAMLKey(t *testing.T) {
	src := []byte(annotatedConfig)
	if !HasYAMLKey(src, "template") {
		t.Error("template is present")
	}
	if HasYAMLKey(src, "title") {
		t.Error("title is absent")
	}
	// An unreadable or non-mapping file answers "yes": the safe response for a
	// caller filling in defaults is to touch nothing.
	for _, broken := range []string{"{{ not yaml\n", "- a\n- b\n", ""} {
		if !HasYAMLKey([]byte(broken), "title") {
			t.Errorf("a file we cannot edit (%q) must not be written to", broken)
		}
	}
}
