package generator

// Configurable _headers generation for Cloudflare Pages (GO-064). The default
// blocks reproduce the historical hardcoded output byte-for-byte; the `headers:`
// config section overrides a default block per pattern or adds new patterns.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// headerBlock is one pattern block in the generated _headers file. Order
// matters twice: Cloudflare applies the first matching value per header, and
// the rendered file must be deterministic across builds.
type headerBlock struct {
	Comment string      // optional comment line rendered above the pattern
	Pattern string      // path pattern, e.g. "/*", "/css/*"
	Headers [][2]string // ordered name/value pairs
}

// defaultHeaderBlocks returns the built-in _headers blocks — the exact content
// SSG has always generated, so an empty `headers:` config changes nothing.
func defaultHeaderBlocks() []headerBlock {
	cacheYear := [2]string{"Cache-Control", "public, max-age=31536000, immutable"}
	cacheHour := [2]string{"Cache-Control", "public, max-age=3600"}
	return []headerBlock{
		{
			Comment: "Security headers for all pages",
			Pattern: "/*",
			Headers: [][2]string{
				{"X-Content-Type-Options", "nosniff"},
				{"X-Frame-Options", "DENY"},
				{"X-XSS-Protection", "1; mode=block"},
				{"Referrer-Policy", "strict-origin-when-cross-origin"},
				{"Permissions-Policy", "geolocation=(), microphone=(), camera=()"},
			},
		},
		{Comment: "Cache static assets for 1 year", Pattern: "/css/*", Headers: [][2]string{cacheYear}},
		{Pattern: "/js/*", Headers: [][2]string{cacheYear}},
		{Pattern: "/images/*", Headers: [][2]string{cacheYear}},
		{Pattern: "/media/*", Headers: [][2]string{cacheYear}},
		{Comment: "Cache HTML pages for 1 hour", Pattern: "/*.html", Headers: [][2]string{cacheHour}},
		{Pattern: "/", Headers: [][2]string{cacheHour}},
	}
}

// mergeHeaderBlocks merges config overrides over the default blocks. A pattern
// present in overrides replaces that default block's headers entirely (keeping
// its position); unknown patterns are appended, sorted alphabetically. Header
// names inside override blocks are sorted too — YAML maps carry no order, and
// the output must be reproducible. defaultsOff drops the defaults entirely.
func mergeHeaderBlocks(defaults []headerBlock, overrides map[string]map[string]string, defaultsOff bool) []headerBlock {
	var blocks []headerBlock
	used := make(map[string]bool, len(overrides))
	if !defaultsOff {
		for _, b := range defaults {
			if hdrs, ok := overrides[b.Pattern]; ok {
				used[b.Pattern] = true
				blocks = append(blocks, headerBlock{Pattern: b.Pattern, Headers: sortedHeaderPairs(hdrs)})
				continue
			}
			blocks = append(blocks, b)
		}
	}
	extra := make([]string, 0, len(overrides))
	for pattern := range overrides {
		if !used[pattern] {
			extra = append(extra, pattern)
		}
	}
	sort.Strings(extra)
	for _, pattern := range extra {
		blocks = append(blocks, headerBlock{Pattern: pattern, Headers: sortedHeaderPairs(overrides[pattern])})
	}
	return blocks
}

// sortedHeaderPairs flattens a header map into name/value pairs sorted by name.
func sortedHeaderPairs(hdrs map[string]string) [][2]string {
	names := make([]string, 0, len(hdrs))
	for name := range hdrs {
		names = append(names, name)
	}
	sort.Strings(names)
	pairs := make([][2]string, 0, len(names))
	for _, name := range names {
		pairs = append(pairs, [2]string{name, hdrs[name]})
	}
	return pairs
}

// renderHeadersFile renders blocks in the Cloudflare/Netlify _headers format.
func renderHeadersFile(blocks []headerBlock) string {
	var b strings.Builder
	b.WriteString("# Cloudflare Pages Headers\n# Generated by SSG\n")
	for _, block := range blocks {
		b.WriteString("\n")
		if block.Comment != "" {
			b.WriteString("# " + block.Comment + "\n")
		}
		b.WriteString(block.Pattern + "\n")
		for _, h := range block.Headers {
			b.WriteString("  " + h[0] + ": " + h[1] + "\n")
		}
	}
	return b.String()
}

// generateHeadersFile writes the merged _headers file into the output root.
func (g *Generator) generateHeadersFile() error {
	blocks := mergeHeaderBlocks(defaultHeaderBlocks(), g.config.Headers, g.config.HeadersDefaultsOff)
	content := renderHeadersFile(blocks)
	headersPath := filepath.Join(g.config.OutputDir, "_headers")
	// #nosec G306 -- Web content files need to be world-readable
	if err := os.WriteFile(headersPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing _headers: %w", err)
	}
	return nil
}
