package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// expectedDefaultHeaders is the exact byte content SSG generated before GO-064,
// locking the no-config path to a byte-for-byte regression baseline.
const expectedDefaultHeaders = `# Cloudflare Pages Headers
# Generated by SSG

# Security headers for all pages
/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=()

# Cache static assets for 1 year
/css/*
  Cache-Control: public, max-age=31536000, immutable

/js/*
  Cache-Control: public, max-age=31536000, immutable

/images/*
  Cache-Control: public, max-age=31536000, immutable

/media/*
  Cache-Control: public, max-age=31536000, immutable

# Cache HTML pages for 1 hour
/*.html
  Cache-Control: public, max-age=3600

/
  Cache-Control: public, max-age=3600
`

func TestRenderHeadersFile_DefaultsRegression(t *testing.T) {
	got := renderHeadersFile(mergeHeaderBlocks(defaultHeaderBlocks(), nil, false))
	if got != expectedDefaultHeaders {
		t.Fatalf("default _headers changed:\n--- got ---\n%s\n--- want ---\n%s", got, expectedDefaultHeaders)
	}
}

func TestMergeHeaderBlocks_OverrideReplacesBlock(t *testing.T) {
	overrides := map[string]map[string]string{
		"/*": {"X-Frame-Options": "SAMEORIGIN", "Content-Security-Policy": "default-src 'self'"},
	}
	blocks := mergeHeaderBlocks(defaultHeaderBlocks(), overrides, false)
	if blocks[0].Pattern != "/*" {
		t.Fatalf("expected /* to keep its position, got %q", blocks[0].Pattern)
	}
	// Override replaces the whole block: original security headers are gone.
	if len(blocks[0].Headers) != 2 {
		t.Fatalf("expected 2 overridden headers, got %d", len(blocks[0].Headers))
	}
	// Header names sorted deterministically.
	if blocks[0].Headers[0][0] != "Content-Security-Policy" || blocks[0].Headers[1][0] != "X-Frame-Options" {
		t.Fatalf("headers not sorted: %+v", blocks[0].Headers)
	}
}

func TestMergeHeaderBlocks_AppendsUnknownPatternsSorted(t *testing.T) {
	overrides := map[string]map[string]string{
		"/api/*":   {"Access-Control-Allow-Origin": "*"},
		"/admin/*": {"X-Robots-Tag": "noindex"},
	}
	blocks := mergeHeaderBlocks(defaultHeaderBlocks(), overrides, false)
	// The two new patterns come after the defaults, alphabetically ordered.
	last := blocks[len(blocks)-2:]
	if last[0].Pattern != "/admin/*" || last[1].Pattern != "/api/*" {
		t.Fatalf("appended patterns not sorted: %q, %q", last[0].Pattern, last[1].Pattern)
	}
}

func TestMergeHeaderBlocks_DefaultsOff(t *testing.T) {
	overrides := map[string]map[string]string{"/*": {"X-Frame-Options": "DENY"}}
	blocks := mergeHeaderBlocks(defaultHeaderBlocks(), overrides, true)
	if len(blocks) != 1 || blocks[0].Pattern != "/*" {
		t.Fatalf("defaults_off should leave only the override, got %+v", blocks)
	}
}

func TestGenerateHeadersFile_WritesFile(t *testing.T) {
	dir := t.TempDir()
	g := &Generator{config: Config{OutputDir: dir}}
	if err := g.generateHeadersFile(); err != nil {
		t.Fatalf("generateHeadersFile: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "_headers"))
	if err != nil {
		t.Fatalf("reading _headers: %v", err)
	}
	if !strings.Contains(string(data), "X-Content-Type-Options: nosniff") {
		t.Fatalf("unexpected _headers content:\n%s", data)
	}
}
