package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// expectedDefaultHeaders is the exact byte content of the no-config path, a
// byte-for-byte regression baseline. It matched what SSG generated before
// GO-064 until #287 allowed the site's own origin in Permissions-Policy.
const expectedDefaultHeaders = `# Cloudflare Pages Headers
# Generated by SSG

# Security headers for all pages
/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(self), microphone=(self), camera=(self)

# Cache static assets for 1 year
/css/*
  Cache-Control: public, max-age=31536000, immutable

/js/*
  Cache-Control: public, max-age=31536000, immutable

/images/*
  Cache-Control: public, max-age=31536000, immutable

/media/*
  Cache-Control: public, max-age=31536000, immutable

# Cache HTML pages for 1 hour
/*.html
  Cache-Control: public, max-age=3600

/
  Cache-Control: public, max-age=3600
`

func TestRenderHeadersFile_DefaultsRegression(t *testing.T) {
	got := renderHeadersFile(mergeHeaderBlocks(defaultHeaderBlocks(), nil, false))
	if got != expectedDefaultHeaders {
		t.Fatalf("default _headers changed:\n--- got ---\n%s\n--- want ---\n%s", got, expectedDefaultHeaders)
	}
}

// TestMergeHeaderBlocks_OverrideMergesIntoBlock — #287. Changing one policy must
// not drop the four security headers the override did not mention.
func TestMergeHeaderBlocks_OverrideMergesIntoBlock(t *testing.T) {
	overrides := map[string]map[string]string{
		"/*": {
			"permissions-policy":         "geolocation=(self)",
			"X-XSS-Protection":           "",
			"Content-Security-Policy":    "default-src 'self'",
			"Cross-Origin-Opener-Policy": "same-origin",
			"X-Removed-Nothing":          " ",
		},
	}
	blocks := mergeHeaderBlocks(defaultHeaderBlocks(), overrides, false)
	if blocks[0].Pattern != "/*" || blocks[0].Comment == "" {
		t.Fatalf("expected /* to keep its position and comment, got %+v", blocks[0])
	}
	want := [][2]string{
		{"X-Content-Type-Options", "nosniff"},
		{"X-Frame-Options", "DENY"},
		{"Referrer-Policy", "strict-origin-when-cross-origin"},
		{"permissions-policy", "geolocation=(self)"},
		{"Content-Security-Policy", "default-src 'self'"},
		{"Cross-Origin-Opener-Policy", "same-origin"},
	}
	got := blocks[0].Headers
	if len(got) != len(want) {
		t.Fatalf("headers = %+v, want %+v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("header %d = %v, want %v", i, got[i], want[i])
		}
	}
}

func TestMergeHeaderBlocks_AppendsUnknownPatternsSorted(t *testing.T) {
	overrides := map[string]map[string]string{
		"/api/*":   {"Access-Control-Allow-Origin": "*"},
		"/admin/*": {"X-Robots-Tag": "noindex"},
	}
	blocks := mergeHeaderBlocks(defaultHeaderBlocks(), overrides, false)
	// The two new patterns come after the defaults, alphabetically ordered.
	last := blocks[len(blocks)-2:]
	if last[0].Pattern != "/admin/*" || last[1].Pattern != "/api/*" {
		t.Fatalf("appended patterns not sorted: %q, %q", last[0].Pattern, last[1].Pattern)
	}
}

func TestMergeHeaderBlocks_DefaultsOff(t *testing.T) {
	overrides := map[string]map[string]string{"/*": {"X-Frame-Options": "DENY"}}
	blocks := mergeHeaderBlocks(defaultHeaderBlocks(), overrides, true)
	if len(blocks) != 1 || blocks[0].Pattern != "/*" {
		t.Fatalf("defaults_off should leave only the override, got %+v", blocks)
	}
}

func TestGenerateHeadersFile_WritesFile(t *testing.T) {
	dir := t.TempDir()
	g := &Generator{config: Config{OutputDir: dir}}
	if err := g.generateHeadersFile(); err != nil {
		t.Fatalf("generateHeadersFile: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "_headers"))
	if err != nil {
		t.Fatalf("reading _headers: %v", err)
	}
	if !strings.Contains(string(data), "X-Content-Type-Options: nosniff") {
		t.Fatalf("unexpected _headers content:\n%s", data)
	}
}
