package generator

// Redirects engine (GO-063): the `redirects:` config section plus frontmatter
// `aliases:` become a real Cloudflare/Netlify `_redirects` file — 301s with
// splat/placeholder support, build-time chain flattening and validation —
// replacing the historical empty file.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// RedirectRule is one `_redirects` entry. From/To accept the shared
// Cloudflare/Netlify syntax: exact paths, `/old/*` splats with `:splat` in To,
// and `:placeholder` segments. Status 0 defaults to 301; 410 marks a gone page.
// Force appends `!` (shadow an existing file — honoured by Netlify only).
type RedirectRule struct {
	From   string
	To     string
	Status int
	Force  bool
}

// Cloudflare Pages `_redirects` limits (documented caps, warned when exceeded).
const (
	cfMaxStaticRedirects  = 2000
	cfMaxDynamicRedirects = 100
	maxRedirectChainHops  = 10
)

// redirectsFileHeader keeps the historical file preamble byte-identical for
// builds with no rules.
const redirectsFileHeader = `# Cloudflare Pages Redirects
# Generated by SSG
# Format: /source /destination [status]

# Trailing slash normalization handled by Cloudflare automatically
`

// isDynamicRedirect reports whether a From pattern uses splats or placeholders.
func isDynamicRedirect(from string) bool {
	return strings.Contains(from, "*") || strings.Contains(from, ":")
}

// normalizeRedirects fills defaults (status 301) and trims whitespace.
func normalizeRedirects(rules []RedirectRule) []RedirectRule {
	out := make([]RedirectRule, 0, len(rules))
	for _, r := range rules {
		r.From = strings.TrimSpace(r.From)
		r.To = strings.TrimSpace(r.To)
		if r.Status == 0 {
			r.Status = 301
		}
		if r.From == "" {
			continue
		}
		out = append(out, r)
	}
	return out
}

// flattenRedirectChains resolves exact-rule chains (A→B→C becomes A→C) so a
// visitor takes one hop instead of several — the chained-redirect SEO penalty
// the rules were written to avoid. Wildcard rules are left untouched (pattern
// algebra is out of scope; validateRedirects warns instead). Cycles are a
// config error; chains deeper than maxRedirectChainHops too.
func flattenRedirectChains(rules []RedirectRule) ([]RedirectRule, error) {
	exact := make(map[string]RedirectRule, len(rules))
	for _, r := range rules {
		if !isDynamicRedirect(r.From) && r.Status != 410 {
			if _, dup := exact[r.From]; !dup {
				exact[r.From] = r
			}
		}
	}
	out := make([]RedirectRule, len(rules))
	copy(out, rules)
	for i, r := range out {
		if isDynamicRedirect(r.From) || r.Status == 410 {
			continue
		}
		seen := map[string]bool{r.From: true}
		to := r.To
		for hops := 0; ; hops++ {
			if hops > maxRedirectChainHops {
				return nil, fmt.Errorf("redirect chain from %q exceeds %d hops", r.From, maxRedirectChainHops)
			}
			next, ok := exact[to]
			if !ok || isDynamicRedirect(to) {
				break
			}
			if seen[to] {
				return nil, fmt.Errorf("redirect cycle detected involving %q", to)
			}
			seen[to] = true
			to = next.To
		}
		out[i].To = to
	}
	return out, nil
}

// validateRedirects returns human-readable warnings: duplicate sources, wildcard
// rules shadowing later rules, `:splat` without a `*` source, unsupported status
// codes and the Cloudflare Pages rule caps. Warnings never fail the build —
// targets may be external or served by a Worker.
func validateRedirects(rules []RedirectRule) []string {
	var warnings []string
	seenFrom := make(map[string]bool, len(rules))
	staticCount, dynamicCount := 0, 0
	for i, r := range rules {
		if seenFrom[r.From] {
			warnings = append(warnings, fmt.Sprintf("duplicate redirect source %q — only the first rule applies", r.From))
		}
		seenFrom[r.From] = true
		if isDynamicRedirect(r.From) {
			dynamicCount++
		} else {
			staticCount++
		}
		switch r.Status {
		case 301, 302, 307, 308, 410:
		default:
			warnings = append(warnings, fmt.Sprintf("redirect %q has unsupported status %d (use 301, 302, 307, 308 or 410)", r.From, r.Status))
		}
		if strings.Contains(r.To, ":splat") && !strings.Contains(r.From, "*") {
			warnings = append(warnings, fmt.Sprintf("redirect %q uses :splat in destination but has no * in source", r.From))
		}
		if r.Status != 410 && r.To == "" {
			warnings = append(warnings, fmt.Sprintf("redirect %q has an empty destination", r.From))
		}
		// A wildcard source shadows every later, more specific rule under its prefix.
		if prefix, ok := strings.CutSuffix(r.From, "*"); ok {
			for _, later := range rules[i+1:] {
				if later.From != r.From && strings.HasPrefix(later.From, prefix) {
					warnings = append(warnings, fmt.Sprintf("wildcard redirect %q shadows later rule %q", r.From, later.From))
				}
			}
		}
	}
	if staticCount > cfMaxStaticRedirects {
		warnings = append(warnings, fmt.Sprintf("%d static redirects exceed the Cloudflare Pages limit of %d", staticCount, cfMaxStaticRedirects))
	}
	if dynamicCount > cfMaxDynamicRedirects {
		warnings = append(warnings, fmt.Sprintf("%d dynamic redirects exceed the Cloudflare Pages limit of %d", dynamicCount, cfMaxDynamicRedirects))
	}
	return warnings
}

// renderRedirectsFile renders rules in `/from /to status[!]` format. Exact rules
// come before wildcard rules: Cloudflare evaluates static redirects first
// regardless of file order, and on Netlify (first match wins) this stops a
// wildcard from swallowing the specific rules beneath it. User order is kept
// within each group.
func renderRedirectsFile(rules []RedirectRule) string {
	var b strings.Builder
	b.WriteString(redirectsFileHeader)
	writeRule := func(r RedirectRule) {
		to := r.To
		if to == "" {
			to = "/"
		}
		force := ""
		if r.Force {
			force = "!"
		}
		fmt.Fprintf(&b, "%s %s %d%s\n", r.From, to, r.Status, force)
	}
	wroteAny := false
	for _, group := range [2]bool{false, true} { // exact first, then dynamic
		for _, r := range rules {
			if isDynamicRedirect(r.From) == group {
				if !wroteAny {
					b.WriteString("\n")
					wroteAny = true
				}
				writeRule(r)
			}
		}
	}
	return b.String()
}

// collectRedirects merges config rules with the frontmatter-alias rules
// recorded during page generation (config first — explicit rules win), then
// flattens chains and gathers validation warnings.
func (g *Generator) collectRedirects() ([]RedirectRule, []string, error) {
	rules := normalizeRedirects(g.config.Redirects)
	fromSeen := make(map[string]bool, len(rules))
	for _, r := range rules {
		fromSeen[r.From] = true
	}
	var warnings []string
	for _, alias := range normalizeRedirects(g.aliasRedirects) {
		if fromSeen[alias.From] {
			warnings = append(warnings, fmt.Sprintf("alias %q overridden by an explicit redirects: rule", alias.From))
			continue
		}
		fromSeen[alias.From] = true
		rules = append(rules, alias)
	}
	flattened, err := flattenRedirectChains(rules)
	if err != nil {
		return nil, warnings, err
	}
	warnings = append(warnings, validateRedirects(flattened)...)
	// Exact internal destinations should exist in the output tree (or be
	// another redirect's source, already flattened away above).
	for _, r := range flattened {
		if r.Status == 410 || r.To == "" || isDynamicRedirect(r.To) || !strings.HasPrefix(r.To, "/") {
			continue
		}
		if !g.refResolves(r.To, g.config.OutputDir) {
			warnings = append(warnings, fmt.Sprintf("redirect %q points at %q which does not exist in the output", r.From, r.To))
		}
	}
	return flattened, warnings, nil
}

// generateRedirectsFile writes the merged `_redirects` file into the output
// root. The file is written even when empty, matching historical behaviour.
func (g *Generator) generateRedirectsFile() error {
	rules, warnings, err := g.collectRedirects()
	if err != nil {
		return fmt.Errorf("redirects: %w", err)
	}
	for _, w := range warnings {
		fmt.Printf("   ⚠️  redirects: %s\n", w)
	}
	content := renderRedirectsFile(rules)
	redirectsPath := filepath.Join(g.config.OutputDir, "_redirects")
	// #nosec G306 -- Web content files need to be world-readable
	if err := os.WriteFile(redirectsPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing _redirects: %w", err)
	}
	return nil
}
