package generator

// Wrangler config scaffolding (GO-077). A project that uses workers needs a
// wrangler.toml for `wrangler pages dev` and `wrangler pages deploy` to read
// bindings and the build output dir. Rather than make the user hand-write one,
// SSG generates a starter when workers are configured and none exists — base
// settings plus each worker's own binding requirements, declared in an optional
// wrangler.snippet.toml the worker ships. Existing files are never overwritten.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// wranglerCompatDate is the compatibility date stamped into a generated config.
// A fixed, known-good date keeps generated files reproducible; bump when the
// Workers runtime features the templates rely on move forward.
const wranglerCompatDate = "2024-11-01"

// wranglerConfigNames are the filenames wrangler itself looks for; any present
// one means the project already has a config and SSG must not touch it.
var wranglerConfigNames = []string{"wrangler.toml", "wrangler.jsonc", "wrangler.json"}

// EnsureWranglerConfig writes a starter wrangler.toml into projectDir when
// workerDirs is non-empty and no wrangler config already exists there. It
// returns the path in use and whether it was just created. Idempotent: a
// pre-existing config (or an explicit one passed via wrangler_config) is left
// untouched and reported as created=false.
func EnsureWranglerConfig(projectDir, name, outputDir string, workerDirs []string, explicit string) (string, bool, error) {
	if len(workerDirs) == 0 {
		return "", false, nil
	}
	if explicit != "" {
		return explicit, false, nil // the user pointed at their own config
	}
	for _, n := range wranglerConfigNames {
		p := filepath.Join(projectDir, n)
		if _, err := os.Stat(p); err == nil {
			return p, false, nil
		}
	}

	content, err := renderWranglerConfig(name, outputDir, workerDirs)
	if err != nil {
		return "", false, err
	}
	dest := filepath.Join(projectDir, "wrangler.toml")
	// #nosec G306 -- a config file, world-readable is fine and matches wrangler's own output
	if err := os.WriteFile(dest, []byte(content), 0644); err != nil {
		return "", false, fmt.Errorf("writing %s: %w", dest, err)
	}
	return dest, true, nil
}

// renderWranglerConfig builds the starter config: base settings, then each
// worker's wrangler.snippet.toml (binding/var stubs) appended verbatim.
func renderWranglerConfig(name, outputDir string, workerDirs []string) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by SSG for a Cloudflare Pages project using workers.\n")
	b.WriteString("# Edit freely — SSG never overwrites an existing wrangler config.\n")
	b.WriteString("# Run locally:  ssg --config .ssg.yaml --watch   (starts `wrangler pages dev`)\n")
	b.WriteString("# Deploy:       ssg --config .ssg.yaml --deploy=cloudflare\n\n")
	fmt.Fprintf(&b, "name = %q\n", wranglerName(name))
	fmt.Fprintf(&b, "pages_build_output_dir = %q\n", "./"+filepath.ToSlash(outputDir))
	fmt.Fprintf(&b, "compatibility_date = %q\n", wranglerCompatDate)

	for _, dir := range workerDirs {
		snippet := filepath.Join(dir, "wrangler.snippet.toml")
		data, err := os.ReadFile(snippet) // #nosec G304 -- path from the project's own configured worker dir
		if err != nil {
			continue // a worker without binding needs contributes nothing
		}
		fmt.Fprintf(&b, "\n# ── from %s ──\n", filepath.ToSlash(dir))
		s := strings.TrimRight(string(data), "\n")
		b.WriteString(s)
		b.WriteString("\n")
	}
	return b.String(), nil
}

// wranglerName reduces a site name/domain to a valid wrangler project name
// (lowercase, a-z 0-9 and hyphens). A blank or unusable name falls back to
// "ssg-site".
func wranglerName(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	name = strings.TrimPrefix(strings.TrimPrefix(name, "https://"), "http://")
	var out strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out.WriteRune(r)
		case r == '-' || r == '.' || r == '_' || r == '/':
			out.WriteByte('-')
		}
	}
	trimmed := strings.Trim(out.String(), "-")
	for strings.Contains(trimmed, "--") {
		trimmed = strings.ReplaceAll(trimmed, "--", "-")
	}
	if trimmed == "" {
		return "ssg-site"
	}
	// Cloudflare Pages project names must start with a letter; a domain like
	// "1password.com" would otherwise produce a name starting with a digit.
	if trimmed[0] < 'a' || trimmed[0] > 'z' {
		trimmed = "ssg-" + trimmed
	}
	// …and are capped at 58 characters; trim a trailing hyphen the cut may leave.
	if len(trimmed) > 58 {
		trimmed = strings.TrimRight(trimmed[:58], "-")
	}
	return trimmed
}
